import "./globals.css";
import { Inter } from "next/font/google";
import { Menu } from "~/components/server/Menu";
import { api } from "~/server/api";

const inter = Inter({ subsets: ["latin", "cyrillic"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    await api.whoami.fetch();
    return (
        <html lang="en">
            <body className={inter.className + " bg-fuchsia-950 text-fuchsia-50"}>
                <Menu />
                {children}
            </body>
        </html>
    );
}
